<a href="https://colab.research.google.com/github/andy3964600/API_method/blob/master/numpy_pratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Initializing Different Types of Arrays

In [ ]:
import numpy as np
#all zero matrix
np.zeros((5,5))


array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [ ]:
#all 1 matrix
np.ones((2,5,4),dtype = int)


In [ ]:
#all full matrix
a = np.full((2,3,4),5)
a.shape

(2, 3, 4)

In [ ]:
# Any other number (full_like)
np.full_like(a,4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [ ]:
# Random decimal numbers = array.shape()
np.random.rand(3,4,5)

array([[[0.94913218, 0.16541808, 0.96792706, 0.52189326, 0.94445547],
        [0.46991604, 0.07326783, 0.39531404, 0.68280487, 0.978461  ],
        [0.4171495 , 0.8430752 , 0.05507786, 0.43966079, 0.49414107],
        [0.96418737, 0.17297877, 0.84542999, 0.54531126, 0.5610125 ]],

       [[0.96439936, 0.45243768, 0.91438167, 0.6482995 , 0.86597361],
        [0.19551977, 0.36152407, 0.23309583, 0.00684102, 0.42697465],
        [0.67530623, 0.1426269 , 0.68102088, 0.795254  , 0.45507984],
        [0.09074559, 0.07618704, 0.63208706, 0.10521497, 0.74828906]],

       [[0.47831139, 0.52772334, 0.9490249 , 0.38705248, 0.398383  ],
        [0.25891055, 0.6502737 , 0.71801144, 0.93301878, 0.1916333 ],
        [0.96246704, 0.9565909 , 0.59529901, 0.11734782, 0.13334078],
        [0.79020644, 0.78027077, 0.3292105 , 0.46491728, 0.3777846 ]]])

In [76]:
# Random Integer values = 
np.random.randint(3,5,size= (2,2,2))

array([[[4, 3],
        [3, 3]],

       [[4, 3],
        [3, 3]]])

In [79]:
# The identity matrix
np.identity(10).shape

(10, 10)

In [113]:
# Repeat an array
a = np.array([[4,5,3]])
print(a)
print(a.shape)
r = np.repeat(a,(1,2,5),axis = 1)

print(r)
print(r.shape)

[[4 5 3]]
(1, 3)
[[4 5 5 3 3 3 3 3]]
(1, 8)


In [139]:
output = np.ones([5,5])
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [140]:
output[2,2] = 9

In [141]:
output[1,1:4] = 0
output[2,1] = 0
output[2,3] = 0
output[3,1:4] = 0

In [142]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [143]:
z = np.zeros([3,3])

z[1,1] =9
output[1:4 , 1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [144]:
b= output.copy()

b[2,2] = 100
print(b)
print(output)

[[  1.   1.   1.   1.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   0. 100.   0.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

Linear Algebra

In [150]:
#Matrix x
a= np.ones((2,3))

b = np.full((3,2),2)
print(a)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [154]:
c = np.linalg.det(np.matmul(a,b))
print(c)

0.0


In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [179]:
#dot
#print(np.inner(np.array([[2,1,1],[1,2,3]]),np.array([[3,1],[1,3],[1,2]])))

print(np.outer(np.array([[2,1],[1,2]]),np.array([[3,1],[1,3]])))
print(np.matmul(np.array([[2,1,1],[1,2,3]]),np.array([[3,1],[1,3],[1,2]])))

[[6 2 2 6]
 [3 1 1 3]
 [3 1 1 3]
 [6 2 2 6]]
[[ 8  7]
 [ 8 13]]


In [155]:
# Determinant
c = np.linalg.det(np.matmul(a,b))
print(c)

0.0


Statistics

In [216]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats.shape)
#min element
np.min(stats , axis = 1)

np.min(stats, axis = 1)


(2, 3)


array([1, 4])

In [223]:
#max element
np.max(stats, axis = 0)

array([4, 5, 6])

In [220]:
np.sum(stats, axis = 0)

array([5, 7, 9])

Reorganizing Arrays